---
title: Convolution and Fourier transformation
author: JK
date: '2020-10-22'
slug: convolution-and-fourier-transformation
categories:
  - Math
  - Machine learning
tags:
  - Gilbert Strang
  - Machine learning
  - Math
  - Linear algebra
subtitle: ''
summary: ''
authors: []
lastmod: '2020-10-22T13:34:22+09:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
Convolution is a vector operation on two vectors. 

$$ Convolution \\ c * d = d*c \\ (c*d)_n = \Sigma_{i+j} c_i d_j = \Sigma_i c_i d_{n-i}.$$
This is multiplying polynomials. The parameters of multiplied polynomial become convolution of two polynomials. Fourier transformation expands x base to infinite exponential basis $e^{iwk}$. The **multiplication on x (time) space** becomes **convolutionn on k (frequency) space**.  

If time space is periodic, its Fourier transformation is discrete i.e. Fourier series. If time space is non-periodic, its Fourier transformation is continuous Fourier transformation.  

The Fourier transformation is dual. The relations of **multiplication and convolution** and **periodic and discrete** are dual in time space and frequency space.  

Fourier transformation is changing basis. The changing basis can be done by inner product (for vector space) or integration (function space) with new basis in which are we want move to space. This is why Fourier transformation coefficients calculated by integration with function multiplying basis $e^{iwk}$. 
