---
title: z-Transformation
author: JK
date: '2021-12-05'
slug: []
categories:
  - Math
  - Digital signal processing
tags:
  - Analysis
  - Complex analysis
  - Digital signal processing
subtitle: ''
summary: ''
authors: []
lastmod: '2021-12-05T06:43:46+09:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

The infinite impulse response is a property of a filter of digital signal processing. The filter response of the impulse signal does not end infinitely. The filter can be represented in either the time domain or frequency domain. Time-domain filter modifies time-domain input signal to time-domain output signal. The frequency domain lets us understand or to design the effect of the filter.  

The discrete Fourier transformation $\Sigma^{N-1}_{n=0} x(n)e^{-i2\pi nm/N}$ transforms time domain to frequency domain in the finite impulse response. This transformation changes real base to finite ($n$) periodic orthogonal basis $e^{i2\pi nm/N}$. The transformation is that the function $X(m)$ extracts the coefficients of the basis.  

A complex number has two representations which are the Cartesian plane and polar plane. **The Laplace transformation ($F(s)=\int^{\infty}_{0} f(t)e^{-st}dt$) results in Cartesian plane (s-plane) function $F(s)$. The z-transformation results in polar plane (z-plane) function.** The z-transformation is the inverse power series expansion of the complex function. The original sequence is coefficients of the power series. Then the original sequence transforms into a complex function. Cauchy's integration fomula can reverse z-transformation (https://spinlab.wpi.edu/courses/ece503_2014/2-5inverse_z_transform.pdf). Cauchy's integral remains only $x(n)$ and eliminates other entries when $X(z)$ multiplied by $z^{-n}$. The Laplace transformation solves the differential equations ($f' = sF$) and the z-transformations solves the difference equations ($x(n-1) = z^{-1}X(z)$). The inverse Laplace transformation integrates on a line path of zero to $\infty$ on the imaginary axis which is a superposition on all frequencies. The basis of z-transformation are polynomials ($z^n$) and those of Laplace transformation are exponentials ($e^{st}$). The z-transformation integrates on line path $-\pi$ to $\pi$. The superposition on frequency was done by the power series ($z^{n}, n \in \mathbb{N}$). The different inverse transformations of the Laplace and z-transformation result in different inverse functions and different convergence conditions of the system. The conditions of convergence of  Laplace transformation is the real part of poles are negative and that of z-transformation is absolute values of poles are less than 1 ($\lvert p \rvert < 1,\ p \in \mathbb C$ where p is pole).  

